from turtle import *

def piec(size,kol="orange"):
    pendown()
    fillcolor(kol)
    begin_fill()
    for _ in range(5):
        fd(size)
        lt(360/5)
    end_fill()
    penup()


def dbl(size, kol):
    lt(36)
    piec(size, kol)
    for _ in range(3):
        fd(size)
        lt(360/5)
    lt(180-72)
    piec(size,kol)
    rt(180)
    for _ in range(2):
        lt(72)
        fd(size)
    lt(36)

def up(a):
    lt(36)
    fd(a)
    lt(72)
    fd(a)
    rt(36)
    fd(a)
    lt(72)
    fd(a)
    rt(144)

def poziomo(a):
    lt(36)
    fd(a)
    rt(72)
    fd(a)
    lt(36)

def shape(size,kol):
    dbl(size,kol)
    up(size)
    lt(36)
    bk(size)
    rt(36)
    dbl(size,kol)
    poziomo(size)
    dbl(size,kol)
    poziomo(-size)
    up(size)
    lt(36)
    bk(size)
    rt(36)
    dbl(size,kol)
    poziomo(size)
    dbl(size,kol)
    poziomo(size)
    dbl(size,kol)
    up(size)
    poziomo(-size)
    lt(36)
    bk(size)
    rt(36)
    dbl(size,kol)
    poziomo(size)
    dbl(size,kol)
    up(size)
    lt(36)
    bk(size)
    rt(36)
    dbl(size,kol)


def kwiatek(n):
    rt(36)
    for _ in range(5):
        x=position()
        y=heading()
        shape(n,"orange")
        setposition(x)
        setheading(y)
        lt(36)
        fd(n)
        lt(36)
    pd()
    rt(72)
    fd(n)
    rt(36)
    fd(n)
    rt(72)
    for _ in range(5):
        x=pos()
        y=heading()
        shape(n,"yellow")
        setpos(x)
        setheading(y)
        pd()
        lt(36)
        rt(180-72)
        fd(n)
        lt(72)
        fd(n)
        rt(72)
        fd(n)
        lt(72)
        fd(n)
        rt(72)

tracer(30,0)
kwiatek(20)
update()
done()